services:
  - type: web
    name: datanitiv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CI
        value: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 